name: Release

on:
  push:
    tags:
      - "v*.*.*"   # runs on version tags like v1.0.0

permissions:
  contents: write
  releases: write
jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.28.3'

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential ninja-build

      - name: Configure
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --parallel

      - name: Package binary
        run: |
          mkdir -p dist
          cp build/eyeball dist/
          tar -czf eyeball-${{ github.ref_name }}-linux-x86_64.tar.gz -C dist eyeball

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: eyeball-${{ github.ref_name }}-linux-x86_64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
